In [16]:
import torch 
import numpy as np 
x = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
print(x.shape)
print(x.shape[0])
print(x.shape[1])
softmax_last_dim = torch.softmax(x, dim=-1)
check1 = torch.softmax(x, dim=1)
check = torch.softmax(x,dim=0)
check2 = torch.softmax(x, dim=-2)
print(softmax_last_dim)
print(check1)
print(check)
print(check2)
print(np.exp(4)/(np.exp(4)+np.exp(5)+np.exp(6)))

torch.Size([2, 3])
2
3
tensor([[0.0900, 0.2447, 0.6652],
        [0.0900, 0.2447, 0.6652]])
tensor([[0.0900, 0.2447, 0.6652],
        [0.0900, 0.2447, 0.6652]])
tensor([[0.0474, 0.0474, 0.0474],
        [0.9526, 0.9526, 0.9526]])
tensor([[0.0474, 0.0474, 0.0474],
        [0.9526, 0.9526, 0.9526]])
0.09003057317038045


In [21]:
query = torch.randn(3)
key = torch.rand(3)
attention_weight = torch.dot(query, key)
print(attention_weight)
attention_weight1 = query.dot(key)
print(attention_weight1)

tensor(0.5361)
tensor(0.5361)


In [6]:
import torch
input = torch.randn(6,3)
batch = torch.stack((input, input), dim=0)
print(batch.shape)
batch1 = torch.stack((input, input), dim=1)
print(batch1.shape)
batch2 = torch.stack((input, input), dim=2)
print(batch2.shape)

torch.Size([2, 6, 3])
torch.Size([6, 2, 3])
torch.Size([6, 3, 2])


In [15]:
check = torch.rand(2,3)
check.transpose(1,0).shape

torch.Size([3, 2])

In [13]:
print(batch.transpose(1, 2).shape)
print(batch.transpose(0, 2).shape)

torch.Size([2, 3, 6])
torch.Size([3, 6, 2])


In [17]:
batch.shape

torch.Size([2, 6, 3])

In [20]:
attn = batch @ batch.transpose(1, 2)
attn.shape
# attn2 = batch2 @ batch2.transpose(0, 1)
# attn2.shape

torch.Size([2, 6, 6])

In [4]:
import torch
check = torch.randn(1,2,3,4)
# one, two = check.shape
yay, yup, yas ,one= check.shape
print(one)
# print(two)
print(yay)
print(yup)
print(yas)
print(check.shape)

4
1
2
3
torch.Size([1, 2, 3, 4])
